- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/Cody-DV/infrastructure-project.git
      repository_path: /home/infrastructure-project

  tasks:
    - name: Install packages
      yum: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python-pip

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Copy Service Configuration
      template: src={{ repository_path }}/templates/hello-world.service.j2 dest=/etc/systemd/system/hello-world.service mode=644
      notify:
        - reload systemctl

    - name: Start Service
      service: name=hello-world state=started enabled=yes

    - name: Copy Nginx site
      template: src={{ repository_path }}/templates/hello-world.nginx.j2 dest=/etc/nginx/conf.d/hello-world.conf
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started enabled=yes

  
  handlers:
    - name: reload systemctl
      command: systemctl daemon-reload

    - name: restart nginx
      service: name=nginx state=restarted
